feature/payment
Kevin-Solomon/football-ecommerce pull request #13
Opened 2022-04-02 08:37 UTC by Kevin-Solomon

# Features added : 

- [x] Add dummy Razorpay gateway.

Click on place order to view Razorpay gateway.
[Preview Link]()

2022-04-02 08:48 UTC, mohammed-sas commented on src/pages/Signup/Singup.jsx
>          email,
typo "Signup.jsx"

2022-04-02 08:51 UTC, mohammed-sas requested changes
on successful payment the cart should reset

2022-04-02 12:50 UTC, mohammed-sas approved these changes
Payment functionality is working as expected
Code is clean and modular
PR is good to merge

2022-04-03 12:27 UTC, starver20 commented
Adding item to cart from single-product view is giving some error.

2022-04-03 12:31 UTC, starver20 approved these changes
Other than that, the pr looks good to merge. Good work.

2022-04-03 12:33 UTC, Kevin-Solomon commented
> 

Yup using Font Awesome is a bit unreliable as the network request gives an error sometimes.
Will switch to react icons before submission.

2022-04-04 11:16 UTC, merged